pre-commit hook now only checks for files changed by current git user

diff --git a/scripts/git-hooks/pre-commit b/scripts/git-hooks/pre-commit
--- a/scripts/git-hooks/pre-commit
+++ b/scripts/git-hooks/pre-commit
@@ -1,21 +1,9 @@
 #!/bin/sh
-YOUR_FAULT=false
-FORMATTER_CHECK=$(./scripts/formatter-check.sh)
+FORMATTER_CHECK=$(./scripts/formatter-check.sh --only-own --no-blame --no-dir-headers)
 
 if [ $? != 0 ]; then
-  USERNAME=$(git config user.name)
-  while read -r line; do
-    if [[ $line == *"$USERNAME"* ]]; then
-      echo $line
-      YOUR_FAULT=true
-    fi
-  done <<< "$FORMATTER_CHECK"
-  if [ "$YOUR_FAULT" == true ]; then
-    echo -e "\e[31mFound formatting errors that seem to be introduced by YOU \e[33m😒\e[39m"
-    exit 1
-  else
-    echo -e "\e[33mFound formatting errors that weren't introduced by you, assuming that's okay \e[91m❤️\e[39m"
-    exit 0
-  fi
+  echo -e "\e[31mFound formatting errors that seem to be introduced by YOU \e[33m😒\e[39m"
+  exit 1
+else
+  echo -e "\e[32mFormatting seems fine on your side \e[33m✨\e[39m"
 fi
-echo -e "\e[32mFormatting seems fine \e[33m✨\e[39m"
